// =========================================================
// game.js — pure game state + rules engine.
//
// State shape:
// {
//   seed: number,                // RNG seed that built the deck
//   deck: Card[],                // index 0 = top of deck (next to draw)
//   discard: Card[],             // discarded/used cards (for counts + debug)
//   room: Array<RoomSlot>,       // up to 4 slots in current room
//   resolvedThisRoom: number,    // 0..3
//   potionUsedThisRoom: boolean, // only first potion heals
//   weapon: { value, lastDefeated, stack: Card[] } | null,
//   health: number,              // 0..MAX_HEALTH
//   maxHealth: number,
//   turn: number,                // 1-indexed room counter
//   lastActionWasAvoid: boolean, // enforce no consecutive avoids
//   status: 'playing' | 'won' | 'lost',
//   score: number | null,
//   carryFromPreviousRoom: Card | null
// }
//
// RoomSlot: { card: Card, resolved: boolean, carry: boolean }
// =========================================================

import { buildDungeon, TYPE, cardLabel, rankLabel } from "./deck.js";

export const MAX_HEALTH = 20;
export const ROOM_SIZE = 4;
export const RESOLVE_PER_ROOM = 3;

// ---------------------------------------------------------
// Construction & resets
// ---------------------------------------------------------

export function newGame(seed) {
  const { deck } = buildDungeon(seed);
  const state = {
    seed,
    deck,
    discard: [],
    room: [],
    resolvedThisRoom: 0,
    potionUsedThisRoom: false,
    weapon: null,
    health: MAX_HEALTH,
    maxHealth: MAX_HEALTH,
    turn: 0,                     // becomes 1 on first drawRoom()
    lastActionWasAvoid: false,
    status: "playing",
    score: null,
    carryFromPreviousRoom: null,
    events: [],                  // transient: events generated by latest action
  };
  drawRoom(state);
  return state;
}

// ---------------------------------------------------------
// Events — UI/log read these out of state.events after each action.
// ---------------------------------------------------------
function emit(state, type, payload = {}) {
  state.events.push({ type, ...payload });
}
function resetEvents(state) { state.events = []; }

// ---------------------------------------------------------
// Drawing rooms
// ---------------------------------------------------------

/**
 * Draw cards from the top of the deck until the room has 4 cards,
 * unless the deck is exhausted (in which case the room is shorter
 * and the game ends after we resolve the remaining cards).
 *
 * If a card was carried over from the previous room, it is placed
 * as the first slot of the new room (and marked carry:true).
 */
export function drawRoom(state) {
  if (state.status !== "playing") return;
  state.turn += 1;
  state.resolvedThisRoom = 0;
  state.potionUsedThisRoom = false;
  state.room = [];

  if (state.carryFromPreviousRoom) {
    state.room.push({ card: state.carryFromPreviousRoom, resolved: false, carry: true });
    state.carryFromPreviousRoom = null;
  }

  while (state.room.length < ROOM_SIZE && state.deck.length > 0) {
    const card = state.deck.shift();
    state.room.push({ card, resolved: false, carry: false });
  }

  emit(state, "room-drawn", { turn: state.turn, size: state.room.length });

  // Edge case: deck was already empty before this turn (no cards drawn,
  // no carry). That means we just cleared the dungeon — win.
  checkEndConditions(state);
}

// ---------------------------------------------------------
// Avoid
// ---------------------------------------------------------

export function canAvoid(state) {
  return state.status === "playing"
      && !state.lastActionWasAvoid
      && state.resolvedThisRoom === 0
      && state.room.length === ROOM_SIZE;
}

/**
 * Place all 4 room cards on the BOTTOM of the deck, preserving order
 * (slot 0 goes down first → ends up higher in the bottom pile), then
 * draw a fresh room. Cannot avoid twice in a row.
 */
export function avoidRoom(state) {
  resetEvents(state);
  if (!canAvoid(state)) {
    emit(state, "blocked", { reason: "cannot-avoid" });
    return state;
  }
  // Push slots to the bottom in order.
  for (const slot of state.room) {
    state.deck.push(slot.card);
  }
  emit(state, "avoided", { turn: state.turn });
  state.lastActionWasAvoid = true;
  drawRoom(state);
  return state;
}

// ---------------------------------------------------------
// Card resolution
// ---------------------------------------------------------

/**
 * Resolve the card at room[slotIndex]. The caller (UI) decides which
 * slot to play. Returns the (mutated) state.
 */
export function resolveSlot(state, slotIndex) {
  resetEvents(state);
  if (state.status !== "playing") return state;
  if (slotIndex < 0 || slotIndex >= state.room.length) return state;

  const slot = state.room[slotIndex];
  if (!slot || slot.resolved) return state;

  // After at most RESOLVE_PER_ROOM resolutions in a 4-card room, the
  // leftover slot is carried over. Smaller rooms (end of deck) resolve
  // everything.
  const fullRoom = state.room.length === ROOM_SIZE;
  if (fullRoom && state.resolvedThisRoom >= RESOLVE_PER_ROOM) {
    emit(state, "blocked", { reason: "room-done" });
    return state;
  }

  const card = slot.card;
  switch (card.type) {
    case TYPE.WEAPON: applyWeapon(state, card); break;
    case TYPE.POTION: applyPotion(state, card); break;
    case TYPE.MONSTER: applyMonster(state, card); break;
  }

  slot.resolved = true;
  state.resolvedThisRoom += 1;
  state.lastActionWasAvoid = false;

  // End checks (health may now be ≤ 0).
  if (state.health <= 0) {
    finalize(state);
    return state;
  }

  // After action, decide if we move to a new room.
  maybeAdvanceRoom(state);
  checkEndConditions(state);
  return state;
}

/**
 * Equip the new weapon. Old weapon (and its defeated monster stack)
 * goes to the discard, and the new weapon's history resets.
 *
 * Example:
 *   Before: weapon ♦7 with stack [♣10, ♠9]   → discarded
 *   After:  weapon ♦4, lastDefeated = null, stack = []
 */
function applyWeapon(state, card) {
  if (state.weapon) {
    state.discard.push({ id: `dw-${state.weapon.value}`,
                         type: TYPE.WEAPON, suit: "♦", value: state.weapon.value });
    for (const m of state.weapon.stack) state.discard.push(m);
  }
  state.weapon = { value: card.value, lastDefeated: null, stack: [] };
  emit(state, "equipped", { card });
}

/**
 * Potion (♥): heal by value, capped at maxHealth. ONLY the first potion
 * resolved in a room heals; subsequent potions are discarded with no
 * effect (the "potion restriction").
 *
 * Example:
 *   Health 12, drink ♥8 → 20 (capped). potionUsedThisRoom = true.
 *   Drink ♥5 same room → wasted. Log "Potion wasted".
 */
function applyPotion(state, card) {
  if (state.potionUsedThisRoom) {
    state.discard.push(card);
    emit(state, "potion-wasted", { card });
    return;
  }
  const before = state.health;
  state.health = Math.min(state.maxHealth, state.health + card.value);
  const healed = state.health - before;
  state.potionUsedThisRoom = true;
  state.discard.push(card);
  emit(state, "healed", { card, amount: healed, before, after: state.health });
}

/**
 * Monster (♣/♠): fight with current weapon if allowed (non-increasing
 * rule), else bare-handed.
 *
 * NON-INCREASING WEAPON RULE
 * --------------------------
 * After defeating a monster of value N, the weapon can only be used
 * against monsters of value ≤ N. First fight is unrestricted.
 *
 * Example sequence with weapon ♦6 (lastDefeated starts null):
 *   1) Fight ♣10: allowed (no prior). damage = max(10-6, 0) = 4.
 *      lastDefeated = 10 (only if damage ≤ 0? NO — see rule).
 *      The card is "defeated" once you finish the fight: damage may
 *      be 0 or positive. We mark it defeated whenever the weapon
 *      participated, then stack it on the weapon.
 *   2) Fight ♠9: 9 ≤ 10 → allowed. damage = max(9-6, 0) = 3.
 *      lastDefeated = 9.
 *   3) Fight ♣13: 13 > 9 → MUST go bare-handed. Take 13 damage.
 *      Weapon stack and lastDefeated are unchanged.
 *   4) Fight ♠4: 4 ≤ 9 → allowed via weapon. damage = max(4-6, 0) = 0.
 *      lastDefeated = 4.
 *
 * Implementation note: "defeated" in this codebase means "the weapon
 * was used", regardless of whether residual damage > 0. The original
 * spec lets damage = 0 still defeat the monster.
 */
function applyMonster(state, card) {
  const w = state.weapon;
  const canUseWeapon = !!w
    && (w.lastDefeated === null || card.value <= w.lastDefeated);

  if (canUseWeapon) {
    const damage = Math.max(card.value - w.value, 0);
    if (damage > 0) state.health -= damage;
    // Stack the monster on the weapon and update history.
    w.stack.push(card);
    w.lastDefeated = card.value;
    emit(state, "fought-weapon", {
      card, weaponValue: w.value, damage,
      lastDefeated: w.lastDefeated,
    });
  } else {
    const damage = card.value;
    state.health -= damage;
    // Bare-handed loss/win — the monster is removed (discarded).
    state.discard.push(card);
    const reason = !w ? "no-weapon" : "weapon-locked";
    emit(state, "fought-bare", { card, damage, reason });
  }
}

// ---------------------------------------------------------
// Room/turn flow
// ---------------------------------------------------------

/**
 * After each resolution, decide if the current room is "done".
 * - In a normal 4-card room: after 3 resolutions, the remaining slot
 *   is carried into the next room.
 * - In a smaller "end of deck" room: when every slot is resolved, the
 *   game will end (handled by checkEndConditions).
 */
function maybeAdvanceRoom(state) {
  const fullRoom = state.room.length === ROOM_SIZE;

  if (fullRoom && state.resolvedThisRoom >= RESOLVE_PER_ROOM) {
    const leftover = state.room.find((s) => !s.resolved);
    if (leftover) {
      state.carryFromPreviousRoom = leftover.card;
      leftover.carry = true; // for the final paint before next render
    }
    drawRoom(state);
    return;
  }

  if (!fullRoom) {
    // End-of-deck small room: resolve every card.
    const allResolved = state.room.every((s) => s.resolved);
    if (allResolved) {
      // Nothing left to draw, no carry → game ends in checkEndConditions.
      state.room = [];
    }
  }
}

// ---------------------------------------------------------
// End game & scoring
// ---------------------------------------------------------

function checkEndConditions(state) {
  if (state.status !== "playing") return;
  if (state.health <= 0) { finalize(state); return; }

  // Win: nothing left to do anywhere.
  const noDeck = state.deck.length === 0;
  const noRoom = state.room.length === 0 || state.room.every((s) => s.resolved);
  const noCarry = !state.carryFromPreviousRoom;
  if (noDeck && noRoom && noCarry) {
    finalize(state);
  }
}

function finalize(state) {
  if (state.health <= 0) {
    state.status = "lost";
    // Score = -(sum of monster values remaining in the deck).
    let sum = 0;
    for (const c of state.deck) if (c.type === TYPE.MONSTER) sum += c.value;
    for (const s of state.room) if (!s.resolved && s.card.type === TYPE.MONSTER) sum += s.card.value;
    if (state.carryFromPreviousRoom && state.carryFromPreviousRoom.type === TYPE.MONSTER) {
      sum += state.carryFromPreviousRoom.value;
    }
    state.score = -sum;
    emit(state, "lost", { score: state.score, monstersLeft: sum });
  } else {
    state.status = "won";
    state.score = state.health;
    emit(state, "won", { score: state.score });
  }
}

// ---------------------------------------------------------
// Friendly helpers for the UI
// ---------------------------------------------------------

export function describeWeapon(weapon) {
  if (!weapon) return null;
  return {
    value: weapon.value,
    lastDefeated: weapon.lastDefeated,
    lastDefeatedLabel: weapon.lastDefeated === null ? "—" : rankLabel(weapon.lastDefeated),
    stack: weapon.stack.slice(),
  };
}

export { cardLabel };
